# Generated by Django 6.1.1 on 2026-09-19 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterMaster',
            fields=[
                ('quarter_code', models.CharField(help_text='Primary Key format: 04F/C/1281', max_length=20, primary_key=True, serialize=False)),
                ('quarter_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Quarter Category: A, B, C, or D', max_length=1)),
                ('quarter_number', models.IntegerField(help_text='Numeric component (e.g., 1281). System automatically zero-pads to 4 digits.')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sector 4F', max_length=50, unique=True)),
                ('boundary_coordinates', models.JSONField(blank=True, default=list, help_text='List of coordinate dicts defining the sector polygon boundary')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='e.g., EMP001', max_length=20, unique=True)),
                ('is_active_on_field', models.BooleanField(default=False, help_text='Manager Status Indicator: True = Green Dot (Working), False = Red Dot (Not Working)')),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_status', models.CharField(choices=[('LOCKED', 'Locked'), ('VACANT', 'Vacant'), ('OCCUPIED_AUTHORIZED', 'Occupied (Authorized)'), ('OCCUPIED_UNAUTHORIZED', 'Occupied (Unauthorized / Others)')], max_length=30)),
                ('photo', models.ImageField(upload_to='inspection_photos/')),
                ('remarks', models.TextField(blank=True, help_text='Operator optional notes/remarks space', null=True)),
                ('captured_latitude', models.FloatField(blank=True, null=True)),
                ('captured_longitude', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_location_verified', models.BooleanField(default=False, help_text='Set to True via Shapely Point-in-Polygon check')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Supervisor Approval'), ('APPROVED', 'Approved'), ('RECHECK', 'Sent Back for Recheck')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_feedback', models.TextField(blank=True, help_text='Supervisor feedback notes for rechecks', null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_inspections', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviews', to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='quarters.quartermaster')),
            ],
        ),
        migrations.AddField(
            model_name='quartermaster',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='quarters.sector'),
        ),
    ]
