# Generated by Django 6.1.1 on 2026-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Field Operator (Maker)'), ('SUPERVISOR', 'Supervisor (Checker)'), ('MANAGER', 'Manager')], default='OPERATOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='is_active_on_field',
            field=models.BooleanField(default=False, help_text='Manager Status Indicator: True = Green Dot (Working)'),
        ),
    ]
