# Generated by Django 6.1.1 on 2026-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarters', '0002_operatorprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='allowed_radius_meters',
            field=models.FloatField(default=500.0, help_text='Maximum allowed distance in meters from center for verification (e.g., 500.0)'),
        ),
        migrations.AddField(
            model_name='sector',
            name='center_latitude',
            field=models.FloatField(blank=True, help_text='Sector center latitude (e.g., 23.6688)', null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='center_longitude',
            field=models.FloatField(blank=True, help_text='Sector center longitude (e.g., 86.1489)', null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='is_location_verified',
            field=models.BooleanField(default=False, help_text='Set to True via Haversine radius check'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='is_active_on_field',
            field=models.BooleanField(default=False, help_text='Manager Status Indicator: True = Green Dot (Working), False = Red Dot (Not Working)'),
        ),
    ]
