# Generated by Django 6.1.1 on 2026-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarters', '0003_sector_allowed_radius_meters_sector_center_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprofile',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Field Operator (Maker)'), ('SUPERVISOR', 'Supervisor (Checker)'), ('MANAGER', 'Manager'), ('ADMIN', 'System Administrator')], default='OPERATOR', max_length=20),
        ),
    ]
