# Generated by Django 6.1.1 on 2026-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarters', '0004_alter_operatorprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='is_location_verified',
            field=models.BooleanField(default=False, help_text='Set to True via Hybrid Polygon or Haversine check'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='boundary_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='List of coordinate dicts defining the sector polygon boundary: [{"lat": 23.66, "lng": 86.15}, ...]'),
        ),
    ]
